FORMAT: 1A

# User API
User is a simple API allowing consumers to get car data.

## Group User

Resources related to Users in the API. Returns array of cars objects with following attributes:

+ id - car id
+ userId - user unique id
+ displayName - display name ex. "VW Scirocco"
+ carStatus - Car status ex. "CURRENT"
+ registrationNumber - Reg number ex. "VMN646"

+ Parameters
    + userid (required, number) - ID of the Car in form of an integer


## Cars data [/api/user/2.0/users/{userid}/cars]
Gets user specific car by following parameters:
+ userid (required, number) - ID of the User in form of an integer

### Get incorrect car [GET]
Returns error as there is no random car.
+ Response 400 (application/json)

        {
          "errors" : [
            {
              "code" : "car.not.found",
              "defaultMessage" : "Car not found"
            },
            {
              "code" : "user.not.found",
              "defaultMessage" : "User not found"
            }
          ]
        }



## User 1 with 1 cars [/api/user/2.0/users/1/cars]
Gets user specific car by following parameters:
+ userid (required, number) - ID of the User in form of an integer


### Get user 1 cars [GET]
+ Response 200 (application/json)
    + Body
        
                {
                  "cars" : [
                            {
                              "car": {
                                "id" : "FF3",
                                "userId" : "1",
                                "displayName" : "My car",
                                "carStatus" : "CURRENT",
                                "orderNumber" : null,
                                "deliveryPhaseStatement" : "",
                                "deliveryPhaseType" : null,
                                "deliveryLeadTimeStatement" : null,
                                "ownership" : null,
                                "companyCarLeasedFrom" : null,
                                "financed" : false,
                                "purchaseType" : null,
                                "carDetails" : {
                                  "derivative" : "FOX 55",
                                  "engineCapacity" : 1.2,
                                  "fuelType" : "Petrol",
                                  "hasServicePlan" : null,
                                  "hasWarranty" : null,
                                  "model" : "FOX",
                                  "registrationDate" : "2010-11-30",
                                  "registrationNumber" : "XYZ123",
                                  "transmission" : "Manual",
                                  "vin" : "WVWZZZ5ZZA4118219",
                                  "year" : "2010"
                                },
                                "suppliedByRetailer" : null,
                                "servicedByRetailer" : null,
                                "images" : null,
                                "dateCreated" : "2015-05-08T13:32:10Z",
                                "lastUpdated" : "2015-05-08T13:32:10Z",
                                "isMotDue" : false,
                                "motDue" : null,
                                "links" : {}
                              }
                            } 
                    ]
                }


### Create user for user 1 [POST]
+ Request (application/json)

        {
          "displayName" : "My car",
          "carStatus" : "CURRENT",
          "carDetails" : {
            "registrationNumber" : "XYZ123",
            "model" : "FOX",
            "derivative" : "FOX 55",
            "registrationDate" : "2010-11-30",
            "fuelType" : "Petrol",
            "vin" : "WVWZZZ5ZZA4118219",
            "year" : "2010",
            "engineCapacity" : 1.2,
            "transmission" : "Manual"
          }
        }
        
+ Response 201 (application/json)

        {
          "car": {
            "id" : "FF3",
            "userId" : "111-1111-111",
            "displayName" : "My car",
            "carStatus" : "CURRENT",
            "orderNumber" : null,
            "deliveryPhaseStatement" : "",
            "deliveryPhaseType" : null,
            "deliveryLeadTimeStatement" : null,
            "ownership" : null,
            "companyCarLeasedFrom" : null,
            "financed" : false,
            "purchaseType" : null,
            "carDetails" : {
              "derivative" : "FOX 55",
              "engineCapacity" : 1.2,
              "fuelType" : "Petrol",
              "hasServicePlan" : null,
              "hasWarranty" : null,
              "model" : "FOX",
              "registrationDate" : "2010-11-30",
              "registrationNumber" : "XYZ123",
              "transmission" : "Manual",
              "vin" : "WVWZZZ5ZZA4118219",
              "year" : "2010"
            },
            "suppliedByRetailer" : null,
            "servicedByRetailer" : null,
            "dateCreated" : "2015-05-08T13:32:10Z",
            "lastUpdated" : "2015-05-08T13:32:10Z",
            "isMotDue" : false,
            "motDue" : null,
            "links" : {}
          }
        }
 

## User 2 with 2 car [/api/user/2.0/users/2/cars]
Gets user specific car by following parameters:
+ userid (required, number) - ID of the User in form of an integer


### Get user 2 cars [GET]
Returns a user data of 2 cars.
+ Response 200 (application/json)
    + Body
        
                {
                  "cars" : [
                     {
                              "car": {
                                "id" : "1",
                                "userId" : "2",
                                "displayName" : "My fox",
                                "carStatus" : "CURRENT",
                                "orderNumber" : null,
                                "deliveryPhaseStatement" : "",
                                "deliveryPhaseType" : null,
                                "deliveryLeadTimeStatement" : null,
                                "ownership" : null,
                                "companyCarLeasedFrom" : null,
                                "financed" : false,
                                "purchaseType" : null,
                                "carDetails" : {
                                  "derivative" : "Golf",
                                  "engineCapacity" : 1.2,
                                  "fuelType" : "Petrol",
                                  "hasServicePlan" : null,
                                  "hasWarranty" : null,
                                  "model" : "Golf",
                                  "registrationDate" : "2010-11-30",
                                  "registrationNumber" : "XYZ123",
                                  "transmission" : "Manual",
                                  "vin" : "WVWZZZ5ZZA4118219",
                                  "year" : "2010"
                                },
                                "suppliedByRetailer" : null,
                                "servicedByRetailer" : null,
                                "images" : null,
                                "dateCreated" : "2015-05-08T13:32:10Z",
                                "lastUpdated" : "2015-05-08T13:32:10Z",
                                "isMotDue" : false,
                                "motDue" : null,
                                "links" : {}
                              }
                            } ,
                     {
                              "car": {
                                "id" : "2",
                                "userId" : "2",
                                "displayName" : "My passat",
                                "carStatus" : "CURRENT",
                                "orderNumber" : null,
                                "deliveryPhaseStatement" : "",
                                "deliveryPhaseType" : null,
                                "deliveryLeadTimeStatement" : null,
                                "ownership" : null,
                                "companyCarLeasedFrom" : null,
                                "financed" : false,
                                "purchaseType" : null,
                                "carDetails" : {
                                  "derivative" : "BlueMotion",
                                  "engineCapacity" : 1.2,
                                  "fuelType" : "Petrol",
                                  "hasServicePlan" : null,
                                  "hasWarranty" : null,
                                  "model" : "PASSAT-VIII",
                                  "registrationDate" : "2010-11-30",
                                  "registrationNumber" : "XYZ456",
                                  "transmission" : "Manual",
                                  "vin" : "WVWZZZ5ZZA4118456",
                                  "year" : "2010"
                                },
                                "suppliedByRetailer" : null,
                                "servicedByRetailer" : null,
                                "images" : null,
                                "dateCreated" : "2015-05-08T13:32:10Z",
                                "lastUpdated" : "2015-05-08T13:32:10Z",
                                "isMotDue" : false,
                                "motDue" : null,
                                "links" : {}
                              }
                            }   
                    ],
                    "images" : {
                                    "high" : {
                                        "static-account" : "http://www.volkswagen.co.uk/assets/content/mobile/high/static-account.jpg",
                                        "static-add-car" : "http://www.volkswagen.co.uk/assets/content/mobile/high/static-add-a-car.jpg",
                                        "static-offers" : "http://www.volkswagen.co.uk/assets/content/mobile/high/static-offers.jpg",
                                        "golf" : "http://www.volkswagen.co.uk/assets/content/mobile/high/golf.jpg",
                                        "passat-vii" : "http://www.volkswagen.co.uk/assets/content/mobile/high/passat.jpg"
                                    },
                                    "low"  : {
                                        "static-add-car" : "",
                                        "static-account" : "",
                                        "static-offers" : "",
                                        "golf" : "",
                                        "passat-vii" : ""
                                    }
                              }
                }



## User specific car data - by car id  [/api/user/2.0/users/{userid}/cars/{carid}]
Returns a specific car data, filtered by user id and car id 

### Get invalid car [GET]
Gets user specific car by following parameters:
+ userid (required, number) - ID of the User in form of an integer
+ carid (required, number) - ID of the Car in form of an integer

    
+ Response 400 (application/json)

        {
          "errors" : [
            {
              "code" : "car.not.found",
              "defaultMessage" : "Car not found"
            },
            {
              "code" : "user.not.found",
              "defaultMessage" : "User not found"
            }
          ]
        }


### Edit a car [PATCH]
Updates given car with new values - This is PATCH metod so you can update one or many fields inside carDetails. 
Field displayName is mandatory. 


Sending null values clean the values. 


Sending "" empty string will throw the exception. 

+ Request (application/json)

        {
         "displayName": "name", 
             "carDetails": {  
                   "model": "model",
                   "derivative": "FOX 55",
                   "fuelType": "Petrol",
                   "year": "2010",
                   "engineCapacity": "1.2",
                   "transmission": "Manual"
             }    
        }
        
+ Response 200 (application/json)

        {
          "car": {
            "id" : "12309392992",
            "userId" : "111-1111-111",
            "displayName" : "My car",
            "carStatus" : "PREVIOUS",
            "orderNumber" : null,
            "deliveryPhaseStatement" : "",
            "deliveryPhaseType" : null,
            "deliveryLeadTimeStatement" : null,
            "ownership" : null,
            "companyCarLeasedFrom" : null,
            "financed" : false,
            "purchaseType" : null,
            "carDetails" : {
              "derivative" : "FOX 55",
              "engineCapacity" : 1.2,
              "fuelType" : "Petrol",
              "hasServicePlan" : null,
              "hasWarranty" : null,
              "model" : "FOX",
              "registrationDate" : "2010-11-30",
              "registrationNumber" : "XYZ123",
              "transmission" : "Manual",
              "vin" : "WVWZZZ5ZZA4118219",
              "year" : "2010"
            },
            "suppliedByRetailer" : null,
            "servicedByRetailer" : null,
            "images" : null,
            "dateCreated" : "2015-05-08T13:32:10Z",
            "lastUpdated" : "2015-05-08T13:32:10Z",
            "isMotDue" : false,
            "motDue" : null,
            "links" : {},
            
            "servicePlan" : {
                "product" : "Fixed Price Servicing",
                "startDate" : "2012-03-01",
                "endDate" : "2015-02-28",
                "contractLength" : 36
            },        
            "financePlan" : {
                "productDescription" : "Hire Purchase",
                "startDate" : "2013-03-15",
                "endDate" : "2016-03-14"
             },
            "serviceHistory" : [
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00688",
                    "name" : "Cheltenham Volkswagen"
                  },
                  "serviceDate" : "2010-03-18"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2011-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2012-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2013-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2014-07-20"
                }
            ]  
          }
        }


### Delete a car [DELETE]
Returns HTTP 204 - no body

Deletes user specific car by following parameters:
+ userid (required, number) - ID of the User in form of an integer
+ carid (required, number) - ID of the Car in form of an integer

+ Response 204


## User specific car data - by car id  [/api/user/2.0/users/2/cars/1]
Returns a specific car data, filtered by user id and car id 

### Get user 2 - car 1 data [GET]
Gets user specific car by following parameters:
+ userid (required, number) - ID of the User in form of an integer
+ carid (required, number) - ID of the Car in form of an integer

+ Response 200 (application/json)

        {
          "car": {
                               "id" : "1",
                                "userId" : "2",
                                "displayName" : "My fox",
                                "carStatus" : "CURRENT",
                                "orderNumber" : null,
                                "deliveryPhaseStatement" : "",
                                "deliveryPhaseType" : null,
                                "deliveryLeadTimeStatement" : null,
                                "ownership" : null,
                                "companyCarLeasedFrom" : null,
                                "financed" : false,
                                "purchaseType" : null,
                                "carDetails" : {
                                  "derivative" : "Golf",
                                  "engineCapacity" : 1.2,
                                  "fuelType" : "Petrol",
                                  "hasServicePlan" : null,
                                  "hasWarranty" : null,
                                  "model" : "Golf",
                                  "registrationDate" : "2010-11-30",
                                  "registrationNumber" : "XYZ123",
                                  "transmission" : "Manual",
                                  "vin" : "WVWZZZ5ZZA4118219",
                                  "year" : "2010"
                                },
                                "suppliedByRetailer" : null,
                                "servicedByRetailer" : null,
                                "images" : null,
                                "dateCreated" : "2015-05-08T13:32:10Z",
                                "lastUpdated" : "2015-05-08T13:32:10Z",
                                "isMotDue" : false,
                                "motDue" : null,
                                "links" : {},
            
            "servicePlan" : {
                "product" : "Fixed Price Servicing",
                "startDate" : "2012-03-01",
                "endDate" : "2015-02-28",
                "contractLength" : 36
            },        
            "financePlan" : {
                "productDescription" : "Hire Purchase",
                "startDate" : "2013-03-15",
                "endDate" : "2016-03-14"
             },
            "serviceHistory" : [
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00688",
                    "name" : "Cheltenham Volkswagen"
                  },
                  "serviceDate" : "2010-03-18"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2011-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2012-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2013-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2014-07-20"
                }
            ]   
          }
        }

## User specific car data - by car id  [/api/user/2.0/users/2/cars/2]
Returns a specific car data, filtered by user id and car id 

### Get user 2 - car 2 data [GET]
Gets user specific car by following parameters:
+ userid (required, number) - ID of the User in form of an integer
+ carid (required, number) - ID of the Car in form of an integer

+ Response 200 (application/json)

        {
          "car": {
                                "id" : "2",
                                "userId" : "2",
                                "displayName" : "My passat",
                                "carStatus" : "CURRENT",
                                "orderNumber" : null,
                                "deliveryPhaseStatement" : "",
                                "deliveryPhaseType" : null,
                                "deliveryLeadTimeStatement" : null,
                                "ownership" : null,
                                "companyCarLeasedFrom" : null,
                                "financed" : false,
                                "purchaseType" : null,
                                "carDetails" : {
                                  "derivative" : "BlueMotion",
                                  "engineCapacity" : 1.2,
                                  "fuelType" : "Petrol",
                                  "hasServicePlan" : null,
                                  "hasWarranty" : null,
                                  "model" : "PASSAT-VIII",
                                  "registrationDate" : "2010-11-30",
                                  "registrationNumber" : "XYZ456",
                                  "transmission" : "Manual",
                                  "vin" : "WVWZZZ5ZZA4118456",
                                  "year" : "2010"
                                },
                                "suppliedByRetailer" : null,
                                "servicedByRetailer" : null,
                                "images" : null,
                                "dateCreated" : "2015-05-08T13:32:10Z",
                                "lastUpdated" : "2015-05-08T13:32:10Z",
                                "isMotDue" : false,
                                "motDue" : null,
                                "links" : {},
            
            "servicePlan" : {
                "product" : "Fixed Price Servicing",
                "startDate" : "2012-03-01",
                "endDate" : "2015-02-28",
                "contractLength" : 36
            },        
            "financePlan" : {
                "productDescription" : "Hire Purchase",
                "startDate" : "2013-03-15",
                "endDate" : "2016-03-14"
             },
            "serviceHistory" : [
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00688",
                    "name" : "Cheltenham Volkswagen"
                  },
                  "serviceDate" : "2010-03-18"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2011-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2012-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2013-07-20"
                },
                {
                  "servicedByRetailer" : {
                    "dealerNo" : "00548",
                    "name" : "Inchcape Volkswagen Chester"
                  },
                  "serviceDate" : "2014-07-20"
                }
            ]   
          }
        }

## Group Car reg lookup
Returns car details by following parameters:
+ regNo (required, string) - Car registration number in form of an String

## Car details for reg number [/api/user/2.0/users/userId/car/details/XYZ123]
### Get car details for valid reg number [GET]
Returns car details for valid registration number XYZ123
+ Response 200 (application/json)

        {
          "carDetails" : {
            "registrationNumber" : "XYZ123",
            "model" : "FOX",
            "derivative" : "FOX 55",
            "registrationDate" : "2010-11-30",
            "fuelType" : "Petrol",
            "vin" : "WVWZZZ5ZZA4118219",
            "year" : "2010",
            "engineCapacity" : 1.2,
            "transmission" : "Manual"
          }
        }

## Car details for reg number [/api/user/2.0/users/userId/car/details/{regNo}]
### Get car details for invalid reg number [GET]
Returns error for invalid registration number
+ Response 400 (application/json)

        {
          "errors" : [
            {
              "code" : "car.not.found",
              "defaultMessage" : "Car not found"
            }
          ]
        }

## Car details for reg number [/api/user/2.0/users/userId/car/details/XXX009]
### Get car details for invalid reg number [GET]
Returns error for non VW vechicle for reg number XXX009
+ Response 400 (application/json)

        {
          "errors" : [
            {
              "code" : "not-a-vw-vehicle",
              "defaultMessage" : "Car is not VW vechicle"
            }
          ]
        }
        
        
## Group Owner details
Owner details section


## Owner details endpoint [/api/user/2.0/users/{userId}/cars/{carId}/owner]
### Get owner details for given user and car id [GET]
Returns error as no action by default 
+ Response 400 (application/json)

        {
          "errors" : [
            {
              "code" : "car.not.found",
              "defaultMessage" : "Car not found"
            },
            {
              "code" : "user.not.found",
              "defaultMessage" : "User not found"
            }
          ]
        }

## Owner details endpoint [/api/user/2.0/users/1/cars/1/owner]
### Get owner details for given user and car id [POST]
Returns owner details for specific user 1

+ Request (application/json)

        {
          "postCode" : "GL542EB",
          "lastName" : "Quinn"
        }

+ Response 201 (application/json)

        {
          "ownerDetails" : {
            "postCode" : "GL542EB",
            "lastName" : "Quinn",
            "carId" : "1"
          }
        }


## Group Configured cars
User configured cars section


## User configured cars endpoint [/api/user/entries/user/1/type/configuration/]
Returns list of confirured cars 
### Get configured cars for given user [GET]
Request Headers x-auth-token: A_VALID_AUTH_TOKEN

+ Request (application/json)

    + Headers
    
            x-auth-token: ZDIxNGM4OGMtZDgxNy00NDljLThkMmQtM2E0ODE5YTM2NjkxOjE0MDUxNzk1MzczMjA6NmU3NGQ1OGJjZWVkYjhhYTljYWQyZjc1NjNmNjNiNWFlNDNmZGI0M2Q5YjNlZTk4MGJlZGFhY2Y3MzY1YWY5Ng==
            
+ Response 200 (application/json)
    
        [
            {
                "id": "51068598-f495-460b-8940-e0296093f347",
                "dateCreated": "2015-03-12T16:05:26Z",
                "lastModified": "2015-03-12T16:05:26Z",
                "owner": {
                    "id": "610082d5-8015-4ea9-aa4e-6feb76f1d0f6",
                    "type": "user",
                    "entryVersion": "1.0.0"
                },
                "type": "configuration",
                "entryVersion": "1.0.0",
                "data": {
                    "upholstery": "n7d",
                    "model": "golf-vii",
                    "secured": true,
                    "paint": "2t2t",
                    "trimWebName": "Golf R-Line",
                    "section": "overview",
                    "price": 28125,
                    "derivative": 2116,
                    "showroomsDerivativeName": "Golf R-Line BlueMotion Technology 2.0 TDI 150PS 6spd 3dr Man",
                    "name": "Test",
                    "context": "preview",
                    "trim": 2112,
                    "ccd": false,
                    "options": "2pu.pi1.znd"
                },
                "links": {
                    "self": {
                        "href": "http://192.168.33.10:8090/api/user/entries/51068598-f495-460b-8940-e0296093f347",
                        "type": "application/json"
                    },
                    "owner": {
                        "href": "http://192.168.33.10:8090/api/user/entries/610082d5-8015-4ea9-aa4e-6feb76f1d0f6",
                        "type": "application/json"
                    }
                }
            }
        ]
        

# Service booking API
    Service booking API endpoint

## Work required [/api/user/booking/work-required]
### Fetch list of work required [POST]
+ Request (application/json)

        {
            "dealerNumber": "00400",
            "fuelType": "Petrol",
            "transmission": "Manual",
            "engineCapacity": "1",
            "engineCode": "AAA",
            "year": "2010",
            "isLease": "false",
            "derivative": "New Polo SE 1.2 TSI 90PS 5-speed Manual 5 Door",
            "isRTCRetailer": "true"
        }
        
+ Response 200 (application/json)

       {
  "Servicing and MOT testing": [
    [
      {
        "additionalInformation": "Basic servicing of your Volkswagen vehicle.",
        "category": 1,
        "engineCode": null,
        "groupOrder": "1",
        "id": 81,
        "isRadio": true,
        "jobCode": "MIN",
        "labourHours": 0.7,
        "mot": false,
        "name": "Minor Service",
        "periodicityDescription": "Every 1 year or 10,000 miles",
        "price": 149,
        "serviceId": 1,
        "subHeading": "Servicing and MOT testing",
        "type": "Servicing and MOT testing",
        "typeOrder": 49
      },
      {
        "additionalInformation": "A more detailed service of your Volkswagen. Should be alternated with minor services.",
        "category": 1,
        "engineCode": null,
        "groupOrder": "1",
        "id": 305,
        "isRadio": true,
        "jobCode": "MAJ",
        "labourHours": 1.9,
        "mot": false,
        "name": "Major Service",
        "periodicityDescription": "Every 24 months / 20,000 miles",
        "price": 299,
        "serviceId": 2,
        "subHeading": "Servicing and MOT testing",
        "type": "Servicing and MOT testing",
        "typeOrder": 49
      }
    ]
  ],
  "Scheduled maintenance": [
    [
      {
        "additionalInformation": "Recommended every year, a refresh treatment disinfects the evaporator and air ducts of your air conditioning system safely and effectively.",
        "category": 1,
        "engineCode": null,
        "groupOrder": "2",
        "id": 25621,
        "isRadio": true,
        "jobCode": "ACR",
        "labourHours": 0.2,
        "mot": false,
        "name": "Air-conditioning refresh",
        "periodicityDescription": null,
        "price": 29,
        "serviceId": 49,
        "subHeading": "Air-Conditioning",
        "type": "Scheduled maintenance",
        "typeOrder": 50
      },
      {
        "additionalInformation": "Recommended every two years. Over time your air-conditioning system loses gas. Unless it's replaced, your system will struggle to keep you cool.",
        "category": 1,
        "engineCode": null,
        "groupOrder": "2",
        "id": 1425,
        "isRadio": true,
        "jobCode": "ACS",
        "labourHours": 1,
        "mot": false,
        "name": "Air-conditioning service (includes refresh)",
        "periodicityDescription": "Every 2 years",
        "price": 79,
        "serviceId": 7,
        "subHeading": "Air-Conditioning",
        "type": "Scheduled maintenance",
        "typeOrder": 50
      }
    ],
    [
      {
        "additionalInformation": "The cambelt is one of the hardest working parts of your engine, driving major parts of the engine and keeping everything synchronised. Changing it prevents snaps, cracks and tears which in turn minimises the risk of major engine damage. ",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "3",
        "id": 33679,
        "isRadio": true,
        "jobCode": "CAM",
        "labourHours": 1,
        "mot": false,
        "name": "Cambelt",
        "periodicityDescription": null,
        "price": 399,
        "serviceId": 48,
        "subHeading": "Cambelt",
        "type": "Scheduled maintenance",
        "typeOrder": 50
      },
      {
        "additionalInformation": "The cambelt is one of the hardest working parts of  your engine, driving major parts of the engine and keeping everything synchronised. Changing it prevents snaps, cracks and tears which in turn minimises the risk of major engine damage.",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "3",
        "id": 33680,
        "isRadio": true,
        "jobCode": "CWP",
        "labourHours": 1,
        "mot": false,
        "name": "Cambelt and waterpump",
        "periodicityDescription": null,
        "price": 449,
        "serviceId": 47,
        "subHeading": "Cambelt",
        "type": "Scheduled maintenance",
        "typeOrder": 50
      }
    ],
    [
      {
        "additionalInformation": "This should be done at year 3 and every 2 years after that. Brake fluid must withstand operating temperatures of up to 230C but over time absorbs water which boils at 100C. As the water boils, it turns to compressible vapour which means you won't be able to brake as efficiently.",
        "category": 1,
        "engineCode": null,
        "groupOrder": "4",
        "id": 1201,
        "isRadio": false,
        "jobCode": "BFS",
        "labourHours": 0.5,
        "mot": false,
        "name": "Brake fluid change",
        "periodicityDescription": "Every 2 years",
        "price": 59,
        "serviceId": 6,
        "subHeading": "Other Scheduled Maintenance",
        "type": "Scheduled maintenance",
        "typeOrder": 50
      }
    ]
  ],
  "Unscheduled maintenance": [
    [
      {
        "additionalInformation": "When you brake, the brake pads grip the brake discs that rotate with the wheels, slowing the car down. Both discs and pads can become worn and corroded, so it's vital they are checked regularly and replaced when they are worn at recommended replacement levels. ",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "5",
        "id": 33681,
        "isRadio": true,
        "jobCode": "FBP",
        "labourHours": 0.7,
        "mot": false,
        "name": "Front brake pads",
        "periodicityDescription": null,
        "price": 129,
        "serviceId": 37,
        "subHeading": "Front Brake Pads",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      },
      {
        "additionalInformation": "When you brake, the brake pads grip the brake discs that rotate with the wheels, slowing the car down. Both discs and pads can become worn and corroded, so it's vital they are checked regularly and replaced when they are worn at recommended replacement levels.",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "5",
        "id": 33683,
        "isRadio": true,
        "jobCode": "FBD",
        "labourHours": 0.9,
        "mot": false,
        "name": "Front brake pads and discs",
        "periodicityDescription": null,
        "price": 249,
        "serviceId": 38,
        "subHeading": "Front Brake Pads",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      }
    ],
    [
      {
        "additionalInformation": "When you brake, the brake pads grip the brake discs that rotate with the wheels, slowing the car down. Both discs and pads can become worn and corroded, so it's vital they are checked regularly and replaced when they are worn at recommended replacement levels.",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "6",
        "id": 33682,
        "isRadio": true,
        "jobCode": "RBP",
        "labourHours": 1.3,
        "mot": false,
        "name": "Rear brake pads",
        "periodicityDescription": null,
        "price": 129,
        "serviceId": 39,
        "subHeading": "Rear Brake Pads",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      },
      {
        "additionalInformation": "When you brake, the brake pads grip the brake discs that rotate with the wheels, slowing the car down. Both discs and pads can become worn and corroded, so it's vital they are checked regularly and replaced when they are worn at recommended replacement levels.",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "6",
        "id": 33684,
        "isRadio": true,
        "jobCode": "RBD",
        "labourHours": 1.1,
        "mot": false,
        "name": "Rear brake pads and discs",
        "periodicityDescription": null,
        "price": 249,
        "serviceId": 40,
        "subHeading": "Rear Brake Pads",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      }
    ],
    [
      {
        "additionalInformation": "If your battery has low charge or isn't holding it's charge, it may prevent your car from starting.",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "7",
        "id": 6801,
        "isRadio": false,
        "jobCode": "BAT",
        "labourHours": 0.2,
        "mot": false,
        "name": "Fully fitted battery replacement",
        "periodicityDescription": null,
        "price": 69,
        "serviceId": 31,
        "subHeading": "Other Unscheduled Maintenance",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      },
      {
        "additionalInformation": "Helps to silence engine noise and reduce emissions.    ",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "7",
        "id": 7025,
        "isRadio": false,
        "jobCode": "RES",
        "labourHours": 0.7,
        "mot": false,
        "name": "Fully fitted rear exhaust",
        "periodicityDescription": null,
        "price": 155,
        "serviceId": 32,
        "subHeading": "Other Unscheduled Maintenance",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      },
      {
        "additionalInformation": "Shock absorbers make your drive smoother and easier.",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "7",
        "id": 7249,
        "isRadio": false,
        "jobCode": "FSA",
        "labourHours": 2.2,
        "mot": false,
        "name": "Fully fitted front shock absorbers",
        "periodicityDescription": null,
        "price": 275,
        "serviceId": 33,
        "subHeading": "Other Unscheduled Maintenance",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      },
      {
        "additionalInformation": "Shock absorbers make your drive smoother and easier.",
        "category": 1,
        "engineCode": "AAA",
        "groupOrder": "7",
        "id": 7473,
        "isRadio": false,
        "jobCode": "RSA",
        "labourHours": 0.9,
        "mot": false,
        "name": "Fully fitted rear shock absorbers",
        "periodicityDescription": null,
        "price": 145,
        "serviceId": 34,
        "subHeading": "Other Unscheduled Maintenance",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      },
      {
        "additionalInformation": "This might be a travel check or a summer check or an EVC.  ",
        "category": 1,
        "engineCode": null,
        "groupOrder": "7",
        "id": 7697,
        "isRadio": false,
        "jobCode": "WHC",
        "labourHours": 1,
        "mot": false,
        "name": "Summer check",
        "periodicityDescription": "",
        "price": 25,
        "serviceId": 35,
        "subHeading": "Other Unscheduled Maintenance",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      },
      {
        "additionalInformation": "This accessory is a device that upgrades an analogue radio to a digital radio.",
        "category": 1,
        "engineCode": null,
        "groupOrder": "7",
        "id": 7921,
        "isRadio": false,
        "jobCode": "DRAD",
        "labourHours": 1,
        "mot": false,
        "name": "Fully fitted digital radio upgrade",
        "periodicityDescription": null,
        "price": 289,
        "serviceId": 36,
        "subHeading": "Other Unscheduled Maintenance",
        "type": "Unscheduled maintenance",
        "typeOrder": 51
      }
    ]
  ]
} 
  